### ISSUE TITLE
Does this no longer work?

### ISSUE THREAD

**Issue by JohnnyPhoton** [AlexeiScherbakov/osklib#2]
OnScreenKeyboard.IsOpened() always returns false. OnScreenKeyboard.Show will hide the keyboard if it is on screen. Using WPF.

**Comment by AlexeiScherbakov** [comment]
Ok, I'll check it, when my sister returns me tablet with sensor screen

10 Фев 2018 г. 1:01 пользователь "JohnnyPhoton" <notifications@github.com>
написал:

**Comment by JohnnyPhoton** [comment]
Thanks. I suspect there is a bug in the latest windows version of the OSK as it doesn't work like it used to.

**Comment by AlexeiScherbakov** [comment]
@JohnnyPhoton , please check new version. If everything is fine - I submit it to NuGet.

Also you can check Osklib.Wpf project for activating Osk for TextBox'es, PasswordBox'es and RichTextBox'es

**Comment by jb455** [comment]
Hi @AlexeiScherbakov, in the source code IsOpened is hardcoded to return false. I guess there's no way to tell if the keyboard is currently open then?

**Comment by AlexeiScherbakov** [comment]
Ops, I forgot about this stub :-D
Check

**Comment by JohnnyPhoton** [comment]
I got busy with other stuff and just got back to this. Seems to be working well, thanks. Sometimes my surface pro just doesn't seem to want to use the OSK unless I disconnect all keyboards but that is the situation I wanted this for. My desktop system has no such issues.

Thanks again!

**Comment by AlexeiScherbakov** [comment]
I have detected that in some cases ITipInvocation COM/WinRT object calls
Toggle without error but no keyboard is showed
After I toggle it manually it begin works as expected for a long time.
Because this thing is not documented feature - I don't know where is a
problem.
I think that if sensor keyboard is not used after computer reboot it need
some additional step to activate in application.

Also you can check updated version :-)

**Comment by JohnnyPhoton** [comment]
Much better now. Seems consistent. Thanks! NuGet is not updated though.
